services:
  - type: web
    name: digital-library-demo
    runtime: python
    rootDir: .
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate && python create_superuser.py && gunicorn Mahi.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: WEB_CONCURRENCY
        value: 2
